using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("NSoft.NFramework.XmlData.Tests for Microsoft .NET Framework 4.0")]
[assembly: AssemblyDescriptionAttribute("NSoft.NFramework XmlData Unit Tests")]
[assembly: AssemblyCompanyAttribute("http://www.nsoft.com")]
[assembly: AssemblyProductAttribute("NSoft.NFramework.XmlData.Tests")]
[assembly: AssemblyCopyrightAttribute("NSoft. All rights reserved.")]
[assembly: AssemblyVersionAttribute("4.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("4.0.0.0")]
[assembly: AssemblyFileVersionAttribute("4.0.0.0")]
[assembly: SatelliteContractVersionAttribute("4.0.0.0")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: NeutralResourcesLanguageAttribute("ko-KR")]
[assembly: ObfuscationAttribute(Feature="string encryption", Exclude=false)]
[assembly: ObfuscationAttribute(Feature="rename symbol names with printable characters", Exclude=false)]

