//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSoft.NFramework.FusionCharts.WebHost.Charts.Combinations {
    
    
    public partial class CombinationChart {
        
        /// <summary>
        /// ChartNameList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList ChartNameList;
        
        /// <summary>
        /// staticChart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NSoft.NFramework.FusionCharts.Web.FusionChart staticChart;
        
        /// <summary>
        /// dynamicChart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NSoft.NFramework.FusionCharts.Web.FusionChart dynamicChart;
        
        /// <summary>
        /// lblChartName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblChartName;
    }
}
