CREATE OR REPLACE PROCEDURE NSoft.GET_EMPLOYEES_BY_DEPT
( 
    P_DEPTNO IN DEPT.DEPTNO%TYPE,
    P_CURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN P_CURSOR FOR
    SELECT * 
      FROM EMP
     WHERE DEPTNO = P_DEPTNO;

END GET_EMPLOYEES_BY_DEPT;

