using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.17020
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliant(true)]
[assembly: ComVisible(false)]
[assembly: AssemblyTitle("NSoft.NFramework.DataServices.Clients for Microsoft .NET Framework 4.0")]
[assembly: AssemblyDescription("NSoft.NFramework DataServices Client")]
[assembly: AssemblyCompany("http://debop.blogspot.com")]
[assembly: AssemblyProduct("NSoft.NFramework.DataServices.Clients")]
[assembly: AssemblyCopyright("Debop. All rights reserved.")]
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: AssemblyInformationalVersion("4.0.0.0")]
[assembly: AssemblyFileVersion("4.0.0.0")]
[assembly: SatelliteContractVersion("4.0.0.0")]
[assembly: AssemblyDelaySign(false)]
[assembly: NeutralResourcesLanguage("ko-KR")]